In [1]:
import torch
import torchvision


In [2]:
#创建矩阵
x = torch.empty(2, 3)
print(x)
x = torch.rand(2, 3)
print(x)
x = torch.zeros(2, 3, dtype = torch.long)
print(x)
y = torch.rand_like(x, dtype = torch.float)
print(y)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5886, 0.2980, 0.9123],
        [0.8492, 0.5648, 0.9989]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0.7536, 0.8188, 0.4514],
        [0.1547, 0.5083, 0.7540]])


In [3]:
#运算
x = torch.rand(2, 3)
y = torch.rand_like(x)
print(x + y)
z = torch.empty_like(x)
z = x + y
print(z)
z = torch.empty_like(x)
torch.add(x, y, out = z)
print(z)
y.add_(x)
print(y)


tensor([[0.7802, 1.3632, 0.5278],
        [0.1929, 0.8303, 1.0318]])
tensor([[0.7802, 1.3632, 0.5278],
        [0.1929, 0.8303, 1.0318]])
tensor([[0.7802, 1.3632, 0.5278],
        [0.1929, 0.8303, 1.0318]])
tensor([[0.7802, 1.3632, 0.5278],
        [0.1929, 0.8303, 1.0318]])


In [7]:
#tensor改变形状
x = torch.rand(2, 3)
print(y)
y = x.view(6)
print(y)
y = x.view(3, 2)
print(y)
y = z.view(-1, 3)  #-1可以看作补余，他的具体值由其他维度来确定
print(y)

#单元素tensor可以提取为标量
x = torch.rand(1)
print(x)
print(x.item())

tensor([[0.2749, 0.5912, 0.1080],
        [0.2716, 0.6981, 0.7224]])
tensor([0.7033, 0.4926, 0.8097, 0.6494, 0.5317, 0.9982])
tensor([[0.7033, 0.4926],
        [0.8097, 0.6494],
        [0.5317, 0.9982]])
tensor([[0.2749, 0.5912, 0.1080],
        [0.2716, 0.6981, 0.7224]])
tensor([0.4678])
0.46775567531585693


In [13]:
#自动微分
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y*y*3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)
print(y.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None


In [21]:
#另一个例子
x = torch.ones(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    print(y, y.data.norm())
    y = y * 2
print(y)
v = torch.tensor([2.0, 1.0, 1.0], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2., 2., 2.], grad_fn=<MulBackward0>) tensor(3.4641)
tensor([4., 4., 4.], grad_fn=<MulBackward0>) tensor(6.9282)
tensor([8., 8., 8.], grad_fn=<MulBackward0>) tensor(13.8564)
tensor([16., 16., 16.], grad_fn=<MulBackward0>) tensor(27.7128)
tensor([32., 32., 32.], grad_fn=<MulBackward0>) tensor(55.4256)
tensor([64., 64., 64.], grad_fn=<MulBackward0>) tensor(110.8512)
tensor([128., 128., 128.], grad_fn=<MulBackward0>) tensor(221.7025)
tensor([256., 256., 256.], grad_fn=<MulBackward0>) tensor(443.4050)
tensor([512., 512., 512.], grad_fn=<MulBackward0>) tensor(886.8100)
tensor([1024., 1024., 1024.], grad_fn=<MulBackward0>)
tensor([1024., 1024., 1024.])
